Racial Balancing
Rotwood-Vale/Ratwood-Keep pull request #160
Opened 2024-06-22 21:16 UTC by Stagrawl

This is broadly up for adjustments, I just wanted to get this up before someone else sneaks something through.

**Changes**

Gender Maluses have been removed. Males now have gendered skills.

Specstats are largely irrelevant as gender stats have been generalised across all races, the one exception for this is Dark Elves. 

I'll fill out more details below.

2024-06-22 21:17 UTC, Stagrawl commented
Humen - +2 Fortune. _Aspiration grants +2 intelligence, as humans are generalists who can do many things._
Dwarf - +2 Constitution, +2 Endurance, +2 Speed. _Stonecunning grants dwarves mining, engineering and masonry._
Half-Orc - +2 Strength, +2 Constitution, +2 Endurance, -2 all else. _Battleready, as horcs are a warlike martial race._
Elf - -1 Strength, +1 Perception, +2 Intelligence, -1 Constitution, +1 Speed.
Dark Elf -
Half Elf - 
Aasimar -
Tiefling -

Axian -
Wildkin -
Halfkin -
Drakian -
Sissean -
Fluvian -
Tabaxi -
Vulpkanin -
Kobold -

2024-06-22 21:20 UTC, Stagrawl commented
I'm not inconsistent, you are. ffs...

2024-06-22 21:24 UTC, Stagrawl commented on code/modules/jobs/job_types/roguetown/roguetown.dm
> +					H.mind.adjust_skillrank(/datum/skill/labor/mining, 1, TRUE)
But Zeth is allowed to slopcode :(

2024-06-22 21:37 UTC, usernameasterisk commented
This is all debatable, but TRAIT_ANTIMAGIC as racial trait? Uh...

2024-06-22 21:54 UTC, usernameasterisk commented
Lizaroids should probably have TRAIT_NASTY_EATER because they are bog crocodiles and therefore should be able to drink dirty water, but I'm unsure how to balance it minding good statset. Skills - swimming, unarmed and farming.

2024-06-22 22:05 UTC, Stagrawl commented
Argument for tiefling antimagic is that they're a profane spieces which corrupt or do not react to manna in the same way other species do.

A lot of devils and extraplanar beings in games like Pathfinder or D&D 3.5 have spell resistance as a part of their template. This would be the main unique things that tieflings get, they have no other specialty.

2024-06-22 22:10 UTC, Stagrawl commented
Racial skills also aren't a given, they're applied to specific races in a way that ties into the powerbudget.

I think the singular exception to this are Tabaxi who have a very niche trait in landing soft, so they've been given more climbing and swimming ability which also ties into their fluff.

2024-06-22 23:07 UTC, KittyNoodle commented
Antimagic as a racial trait is fucking insane
Also whats with the fortune buffs for tiefings and humens

2024-06-22 23:18 UTC, Stagrawl commented
> Antimagic as a racial trait is fucking insane Also whats with the fortune buffs for tiefings and humens

Humens always got fortune as they are Psydon's favourites, they're intended to be generalists who have no particular focus and can choose their own path, so +2 fortune with no downsides. Then I've used their trait slot power budget to give them +2 int until such a time that someone introduces some sort of fast-learner or suitable jack-of-all-trades trait.

Aasimar and Tieflings are both humen subtypes and both touched by extraplanar forces, Aasimar being blessed by the divine and Tiefling having similar unholy advantages. Both also have no other particular leaning.

2024-06-22 23:20 UTC, KittyNoodle commented
Also this pretty much removes all the stat differences which makes things feel very bland, and as a result is a MASSIVE buff to some species like orcs, which get all their bonuses with zero maluses, which compared to dark elves which now have lost their normal elven intelligence stats. and most of the furry races getting the ability to drink bog water.

2024-06-22 23:26 UTC, Stagrawl commented
> Also this pretty much removes all the stat differences which makes things feel very bland, and as a result is a MASSIVE buff to some species like orcs, which get all their bonuses with zero maluses, which compared to dark elves which now have lost their normal elven intelligence stats. and most of the furry races getting the ability to drink bog water.

It... Doesn't remove stat differences, at all. It clearly defines them rather than them being a mess of random numbers.

Orcs... Have downsides. They use the exact same power budget as every other race.

Dark Elves had excess stats which is the reason they were the choice for many powergamer adventurers. ANY adjustment that brings things into balance is going to be a nerf for them. 

**Two** of the furry races get the ability to drink bogwater.

I'm open to further development on this down the line and some of this is explicitly placeholder material.

2024-06-23 03:26 UTC, usernameasterisk commented
Why do elves have skills but humens do not? They both got +4-4 stats and no traits.

2024-06-23 08:52 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/furry/moth.dm
> +	specstats_f = list("strength" = 0, "perception" = 0, "intelligence" = 0, "constitution" = -2, "endurance" = 0, "speed" = 2, "fortune" = 0)
maybe make them have -1 strength -1 end and +2 int/+1 int and +1 per? very boring stats

2024-06-23 08:52 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
> +	specstats_f = list("strength" = 0, "perception" = 1, "intelligence" = -1, "constitution" = -1, "endurance" = 0, "speed" = 1, "fortune" = 1)
getting +1 fortune is unneeded since Tabaxi arent favored by any gods or anything. maybe give them +2 speed instead

2024-06-23 08:52 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm
> +	specstats_f = list("strength" = 0, "perception" = 1, "intelligence" = 0, "constitution" = -1, "endurance" = 1, "speed" = 1, "fortune" = 0)
inconsistent, +3 and -1, need another - or get rid of pointless endurance

2024-06-23 08:52 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
> +	specstats_f = list("strength" = 0, "perception" = 0, "intelligence" = 0, "constitution" = 2, "endurance" = 2, "speed" = -2, "fortune" = 0)
keep +1 strength since they need to mine

2024-06-23 08:52 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
> +	specstats = list("strength" = 0, "perception" = -1, "intelligence" = 2, "constitution" = -1, "endurance" = -1, "speed" = 3, "fortune" = 0) //Gender-Adjusted
+3 speed is fucking insane for little twink drow men. give them another - to endurance at least, or a - to strength

2024-06-23 08:52 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
> +	specstats_f = list("strength" = -1, "perception" = 1, "intelligence" = 2, "constitution" = -1, "endurance" = 0, "speed" = 1, "fortune" = 0)
Elven females should still have at least -3 strength, and high speed. Its literally elf women, they are NOT on par with elf men

2024-06-23 08:52 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
> +	specstats_f = list("strength" = 0, "perception" = 1, "intelligence" = 1, "constitution" = 0, "endurance" = 0, "speed" = 1, "fortune" = 1)
ADD BACK -1 FORTUNE, LITERAL INBREDS.

2024-06-23 08:52 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
> +	specstats_f = list("strength" = 0, "perception" = 0, "intelligence" = 0, "constitution" = 0, "endurance" = 0, "speed" = 0, "fortune" = 2)
i would say, they need -fortune, but your going in a different direction with Tiefs i think so. They are far too boring, at least make them less strong and more smart

2024-06-23 09:12 UTC, Hmeister-real requested changes

2024-06-23 09:12 UTC, Hmeister-real commented on code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
> +	specstats_f = list("strength" = 0, "perception" = 0, "intelligence" = 2, "constitution" = -2, "endurance" = 0, "speed" = 0, "fortune" = 2)
forgot in review. Aasimar are supposed to be overtuned and better than other races in every way other than strength and endurance, and should be much frailer. You made them, equal to humans with a random - to con. buff them again

2024-06-23 12:08 UTC, PTFOperations commented
Please change goblins as well

2024-06-23 16:36 UTC, KKLZ4 commented
Firmly against. An array for racial stats better serves racial balance. https://github.com/Rotwood-Vale/Rotwood-Vale/pull/73

2024-06-23 16:47 UTC, Stagrawl commented
> Firmly against. An array for racial stats better serves racial balance. See my PR here > #73 Traits should only be reserved for patrons, since there's no way to statistically assign a 'value' to something like 'Can drink swampwater', 'takes no fall damage', or 'has a stronger bite' compared to however many points in core stats that would be equivalent to. Skills should exclusively be reserved for roles. Being a dwarf shouldn't mystically impart knowledge of masonry upon me, and likewise, not all wildkin should be able to drink swampwater.

Proposed changes in that PR solve no issues and introduce more, they're also basically so unthematically and mechanically intentful that they may as well have been randomly rolled.

2024-06-23 20:13 UTC, pismorizzo commented
Far prefer the way each race having a minor perk in this PR, rather than just all being incredibly bland with just random stat adjusts than largely don’t matter other than min maxxing strength or speed.

The people complaining that minor perks like drinking bogwater is too strong or weak are failing to understand how each race having something a tad unique helps differentiate them. Especially with several of the furry races already being visually quite similar when wearing armor. The stats are already being adjusted to be in line with the power of the perks so any race should be easily able to be tuned down and keep the perk if it’s deemed too strong.

I will  also say the anti magic trait on tieflings should probably just lowered to a heat damage resist since fireball is basically the only non-vampiric source of magic damage since lightning is just used as a stun.

2024-06-23 20:46 UTC, ApplePlastic commented
> Lizaroids should probably have TRAIT_NASTY_EATER because they are bog crocodiles and therefore should be able to drink dirty water, but I'm unsure how to balance it minding good statset (maybe give them -2 int and spd, they are heavy ass scalie slaves after all). Skills - swimming, unarmed and farming.

PLEASE.

2024-06-24 13:15 UTC, Coolgat3 commented
Giving moths and cats, or anyone at all, for that matter, traits to jump up fucking z levels and jump down z levels freely is incredibly busted and should not be considered for anyone except the jester or werewolf.

2024-06-24 13:23 UTC, Stagrawl commented
The issue with starting off with insanely inaccurate or bad critique is that it makes me want to just disregard everything else.

Gendered skills already exist, that you don’t know this suggests a lack of game knowledge that implies you likely shouldn’t be commenting on this already.

Fortune doesn’t… Exactly work in the way you’re describing. Furthermore the damage of a crit is purely icing. Most crits will remove you from a fight outright or lead to a slow, near unpreventable death.

Cats don’t get zjump. Moths don’t get it “freely” it’s costed as part of their budget.

I’m likely not responding to any more unconstructive comments after this. Suggest an alternative if you have an issue with something. Just saying “NUH-uh!” is pointless and obstructive.

2024-06-24 21:06 UTC, Rasengetsu commented
I like these changes overall tbh. Couple things need some refining or additional coding, such as humans needing a whole-ass trait instead of int, but as it is this looks good to me. God knows I hate the current stats for the majority of races and the massive advantage being female has in all races except drow.

2024-06-28 12:28 UTC, Stagrawl commented
> Holy buffs steve, why are we powercreeping all the races, everything is buffed to more than it should be, "balanced" means that at the end of the stats, it SHOULD equal 0, not +2 or +4 total. ESPECIALLY if they get special traits like JUMPING Z LEVELS AND FALLING WITHOUT BREAKING LIMBS. Because that, is OP. Please fix the stats before continuing with the pr, make sure it's a total of -1 if they get special traits to balance it out, after all moths who can jump and fall with no problem with 0 strength penalty kinda, no, REALLY sounds iffy. Thanks for coming to my ted talk

^

The above commenter was saved from a BlackStone Gitban by the grace of Bob Joga alone.

2024-06-28 12:46 UTC, CVSthePharmacy commented
> The above commenter was saved from a BlackStone Gitban by the grace of Bob Joga alone.

the above commenter is trying to shy away attention from the haphazardly made pr by mentioning their own grudge

2024-06-28 12:51 UTC, CVSthePharmacy commented
also, I can give you a whole new stats list, which would actually be balanced and reasonable

2024-06-28 13:13 UTC, CVSthePharmacy commented
also please remove giving GENDERS a buff just because they are one, wtf man

2024-06-28 13:15 UTC, KKLZ4 commented
I don't tend to agree with CVS, but I absolutely do agree that it's nigh-impossible to quantify what "No fall damage" is equivalent against numerical stat lines. Is it +2 SPD? +3? +4? Is it +1 CON? Likewise, how about something a bit more mundane and less-useful like "Can drink dirty water"? Is that going to be a +1 to CON? or +1 END? +2 even?

Shifting traits to your Patron Deity means we can separate statlines from traits and have an easier time of balancing things. You can't tell me +2 STR, +2 CON and "Strong Bite" is balanced by the fact that Sisseans get -1 SPD and -1 INT. I would argue +2 STR and +2 CON isn't even balanced against -1 SPD and -1 INT, among the various other issues, skills should not be tied to races. A dwarf born in Rockhill who was a barkeep wouldn't mystically be imbued with the knowledge of stoneworking and smithing, that's just- beyond bizzare.

2024-06-28 13:17 UTC, Stagrawl commented
> I don't tend to agree with CVS, but I absolutely do agree that it's nigh-impossible to quantify what "No fall damage" is equivalent against numerical stat lines. Is it +2 SPD? +3? +4? Is it +1 CON? Likewise, how about something a bit more mundane and less-useful like "Can drink dirty water"? Is that going to be a +1 to CON? or +1 END? +2 even?
> 
> Shifting traits to your Patron Deity means we can separate statlines from traits and have an easier time of balancing things. You can't tell me +2 STR, +2 CON and "Strong Bite" is balanced by the fact that Sisseans get -1 SPD and -1 INT. I would argue +2 STR and +2 CON isn't even balanced against -1 SPD and -1 INT, among the various other issues, skills should not be tied to races. A dwarf born in Rockhill who was a barkeep wouldn't mystically be imbued with the knowledge of stoneworking and smithing, that's just- beyond bizzare.

We've discussed all of these points, there's no value to be found in going over them again.

I will point out, your own offered alternative doesn't adress a huge chunk of the concerns you're rasing here.

2024-07-02 14:47 UTC, Hmeister-real commented
why the hell can Lizardfolk breathe underwater. That literally just makes no sense

2024-07-02 22:02 UTC, Stagrawl commented
He's a semiaquatic Egg laying lizard of action He's a scaly little flatfoot Who'll never flinch from a fray He's got more than just mad skill He's got a lizard tail and no bills And the women swoon Whenever they hear him say...

2024-07-05 20:55 UTC, githubuser4141 commented
Why are you removing gendered stats? Stats, being linked to the person's actual body make a whole lot more sense then traits, which means that all males automatically know crafting and wrestling, which are job professions not biological skills, so just magically having training because you have a penis doesn't make much sense at all.

2024-07-08 02:07 UTC, coffeecoffeecoffee commented
Please just allow us to CHOOSE a stat/skill archetype for either gender, so we can have some more effete men and more masculine women if we so choose. It already happens, this just burdens people less in roleplaying it.

2024-07-10 21:18 UTC, atomicplan666 commented
Can't wait to play OP lizard man.

2024-07-12 18:19 UTC, MefAnneFeminene commented
The races are given quite a lot of bonuses, which is weird. Being a different fantasy race shouldn't be too impactful unless you're one of the few vastly different ones. Shortening out the bonuses 

Akula
![image](https://github.com/user-attachments/assets/e393a254-de88-4cfa-a6c4-3bc0f975d261)
Remove strength bonus and this is fine

Wilk-kin
![image](https://github.com/user-attachments/assets/2065eefb-36d6-4266-877b-43d0fc5e5330)
Remove speed bonus and this is fine

half-kin
![image](https://github.com/user-attachments/assets/8d6716e9-2908-4a2e-900c-733259a24b7f)
Remove fortune bonus entirely, change to +1 intelligence, +1 perception, -1 constitution

Drakian
![image](https://github.com/user-attachments/assets/9a50f142-7e04-4b3e-a6bc-0937bd83abeb)
Remove endurance bonus

Kobold
![image](https://github.com/user-attachments/assets/af87d1a9-1425-43a9-b1ed-01d5eafbb7b6)
This is okay

Sissean
![image](https://github.com/user-attachments/assets/47e3002a-c104-41f6-8c7f-c54096d0e67f)
Remove 1 strength or 1 constitution and this is _fine_

Fluvian
![image](https://github.com/user-attachments/assets/d6ea4b28-50dc-41b9-ab57-ecf1adeaa668)
Change to +1 Intelligence, +1 speed, -1 constitution

Tabaxi
![image](https://github.com/user-attachments/assets/00801fe7-6ed8-413b-8f74-d4dc0f1430d9)
Remove fortune buff and this is fine

Vulpkanin
![image](https://github.com/user-attachments/assets/b1685c83-4d23-4fd0-803f-be32b23ac239)
Remove speed buff and this is fine

Dwarf
![image](https://github.com/user-attachments/assets/586cbc81-03e4-4311-a9d6-7a9f8da9098f)
Change to +1 strength, +2 constitution, +1 endurance, -2 speed

Drow
![image](https://github.com/user-attachments/assets/5312a425-e6c2-40e7-977d-6f42ac87e981)
Male: STR 0, PER -1, INT 1, CON 0, END 0, SPD 1
Female: STR 1, PER -1, INT 0, CON 1, END 0, SPD 0
(3 speed is fucking insane, faster than Kobolds)

Elf
![image](https://github.com/user-attachments/assets/79910155-a3aa-4af7-b0f3-ee19f7d4372b)
Remove speed buff and this is fine

Humen
![image](https://github.com/user-attachments/assets/aa341f5b-194e-4b04-a51d-44893e044020)
Remove fortune buff

Aasimar
![image](https://github.com/user-attachments/assets/43e9dd2b-0ff9-4b50-a690-8b81a3773d18)
-1 strength

Half-Elf
![image](https://github.com/user-attachments/assets/1d1e5f48-93b0-417e-bb65-49cf9aae692e)
Remove fortune buff, -1 strength and -1 constitution

Half-Orc
![image](https://github.com/user-attachments/assets/f28b8231-f324-45e7-bd57-10375262c4ac)
Remove fortune debuff or raise speed to 0

Tiefling
![image](https://github.com/user-attachments/assets/29e33cb5-c6ec-4659-a6e0-f6f562650429)
This is begrudgingly okay. The species trait makes up for it.

I'm not gonna get into traits because that's a whole other can of worms, but being able to jump between Zs is bad, and dwarves starting with bonuses to skills is also bad. A race shouldn't just magically be good at masonry or smithing.

2024-07-19 18:49 UTC, zakanater19 commented
+1 speed is more of a buff that +1 str

2024-07-21 08:59 UTC, CalamaBanana commented
Some thoughts:

- All races that get useful traits should have reduced stats in compensation, 
- The leap and "fall damage traits should not work if one is wearing armor. They invalidate much of the map's design
- Elves getting each and every useless skill and nothing else feels off. At least throw them one or two that actually have a use. Perhaps climbing to get into trees or medicine because they are smart, after all? Or a fun trait like leaf-walking so they can live in the trees.
- Female elves got buffed far too much. I enjoyed being weak as fuck so people can't force me to fight. Maybe shift a point to perception, int or speed again.
- Drows already attract a large population of edgy murderhobos, adding even more combat skill to them just makes it worse

2024-07-24 21:08 UTC, EzekyalLegit commented
Removing the fortune bonuses was not the move. Fortune is not nearly as important as you think, some jobs actually add 3 fortune to you just for picking them. Speed is MUCH more powerful a stat than fortune since it affects landing hits, dodging, parrying, movement speed. Its called pretty often.

2024-07-27 10:32 UTC, closed without merging