Druid Buff | Scomm Ring Icon
Rotwood-Vale/Ratwood-Keep pull request #1639
Opened 2024-11-22 09:08 UTC by ProbablyCarl

## About The Pull Request
Provides druids a hefty buff.

Adds them being friendly with the following:
 - Spiders
 - Rats
 - Volves
 - Moles

They're also provided a walking stick by default, with randomized skill in polearms between 1 or 2.

Not related to this PR's main focus, but snuck in, is scomm rings getting a temporary sprite by way of using the scommstone icon. It doesn't have its two special states set, however, and is one icon only. It's not proper at all, but it's something to look at that makes SOME sense, as opposed to it being invisible.

## Why It's Good For The Game
Druids are kind of a forgotten role. I 'unno. This was at the request of a few people, with suggestions from players.

2024-11-22 13:15 UTC, awawaawawaawa commented
> ### 2) Why should this feature be locked to druids? Why not make it modular by setting it as a trait?
> 
> This change would make it much easier to work with for gamemasters, and also paves the way for druids who break tenets of dendor (i.e by abusing their immunity to slay mobs that can't fight back) to have their trait removed. Furthermore, it would allow for the mechanic to be tutorialized naturally, as players tend to check their traits on spawn, they would easily see some immersive message like:
> 
> _"**Dendor's Watch** - I am a companion of Dendor, patron of the wild. Woodland creatures pose no threat to me."_
> 
> Once you saw the text, you would immediately understand you are safe from beasts. Being able to roleplay around the boons your patron has granted you is essential, so this seems like the greatest benefit to the average player if you set it as a trait. (You could achieve a similar thing by simply printing some text in chat when you spawn as druid, but it would often be skipped over as most players do not check that text for changes.)
> 
> Another benefit is that in future a mechanic could even be implemented so that upon violating Dendor's will (butchering a mob for an example that's easy to code) you lost the trait, to promote druidic roleplay where nature is revered rather than exploited. This would not be in the scope of the current PR, but by making the feature a trait you would pave the way for anyone else to add it in future!


A lot of druids like to hunt, I among them. 'Dendor provides' being a common saying among Dendorites as a whole. Hunting is a part of that ethos. I really don't like the idea of Druids being penalized for roaming wild, and hunting prey. Not a fan of that particular bit.

2024-11-22 17:13 UTC, Elli-Skala commented
I imagine moving druids away from fist fighting and wrestling (like every other church caster) and more to pole arms expertise could be interesting. We have the druidic trickery as a crafting option if we wanted to open it more via allowing druids to craft higher teir dendor blessed wooden staffs

2024-11-22 20:43 UTC, Gyrandola requested changes
Druids being friendly with wolves etc is OK I suppose, however:

Druids being not ambushable makes them almost unable to hunt (they aren't necessarily hippies), and also makes them not ambushable by goblins, which most definitely are not creatures of Dendor.

It might be a bit aids to address the aforementioned request, so feel free to atomize the rest of the changes because they are good.

2024-11-23 09:38 UTC, Gyrandola approved these changes

2024-11-23 09:38 UTC, merged