[Port] Eoran stuff from Stonekeep | Acolytes, Templars, Clerics
Rotwood-Vale/Ratwood-Keep pull request #1727
Opened 2024-11-29 14:45 UTC by Vladmar11

Adds Eora Acolytes/Templars/Clerics to the game and associated spells + sprites.

Changed Eora's description. Now Eora is the goddess of love, life and beauty as everything is misleading that Eora and Baota are one and the same.

Spells:

Eoran Bloom:

With a long cooldown and casting time, summon a Eoran Bud to help promote "peace" and pacify people. 

Eoras Curse

Makes the target high and drunk. That's all, yeah.

Robes have alternative version (rightclick on it)

(Credit to monochrome9090 for all of his work on the sprites)

Feat. SayonaraEcho

Plans: 
1) Remove ability to marry people for druids and give this ability to eoran acolytes (from here https://github.com/Darkrp-community/OpenKeep/pull/1038/)
2) Add new sprites for templar's tabards 
3) Review the acolytes/cleric's abilities later (they are too weak)

![4e](https://github.com/user-attachments/assets/3fc6bec9-9c65-4d87-82a2-df14e9e26889)
![im6age](https://github.com/user-attachments/assets/2c03ee12-c7af-419b-b209-0a6a66f3c6a3)

2024-11-29 16:06 UTC, Gyrandola requested changes

2024-11-29 16:06 UTC, Gyrandola commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		if("Eora") //Eora content from stonekeep
Useless comment

2024-11-29 16:06 UTC, Gyrandola commented on code/modules/clothing/rogueclothes/hats/hats.dm
> +			to_chat(user, "<span class='warning'>I feel at peace. <b style='color:pink'>Why would I want anything else?</b></span>")
Spannify this

2024-11-29 16:06 UTC, Gyrandola commented on code/modules/spells/roguetown/acolyte/eora.dm
> +	to_chat(user, "<span class='warning'>The targeted location is blocked. The flowers of Eora refuse to grow.</span>")
Span

2024-11-29 16:06 UTC, Gyrandola commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		target.visible_message("<span class='info'>A purple haze shrouds [target]!</span>", "<span class='notice'>I feel much calmer.</span>")
Span

2024-11-29 18:29 UTC, Gyrandola commented
By spannifying I meant using the span_warning helper instead of raw html

2024-11-29 19:04 UTC, Vladmar11 commented
> By spannifying I meant using the span_warning helper instead of raw html

Got it. Sorry, this is my first job. Is that right?

2024-11-29 20:07 UTC, Coolgat3 commented
What kind of drug? If it's spice, then I'll have you know it has a low chance to crash someone for the entiriety of the round. It also gives -5 fortune, which in combat is an extreme hinderance. Basically an eoran acolyte will be able to give someone -5 fortune ad slit their throat with a thorn or something.

2024-11-29 20:59 UTC, ophaq commented
Please add a spell that is a half second stun where the person jizzes their pants.

2024-11-29 23:00 UTC, Gyrandola commented
fix conflicts and i will test merge this

2024-11-30 13:06 UTC, Vladmar11 commented
> fix conflicts and i will test merge this

Ready to merge

2024-11-30 15:19 UTC, Dilligentdog commented
should give Eoran acolytes the same skill bath wenches get. Fabled lover or whatever the name is. They are followers of the goddess of love afterall

2024-11-30 17:14 UTC, Gyrandola commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		target.visible_message(span_warning("<span class='info'>A purple haze shrouds [target]!</span>"), span_warning("<span class='notice'>I feel much calmer.</span>"))
if you use a span helper, you need to remove the raw html one.

2024-11-30 17:15 UTC, Gyrandola commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		target.visible_message(span_warning("<span class='info'>A purple haze shrouds [target]!</span>"), span_warning("<span class='notice'>I feel much calmer.</span>"))
```suggestion
		target.visible_message(span_info("A purple haze shrouds [target]!"), span_info("I feel much calmer."))
```

2024-11-30 17:15 UTC, Gyrandola commented on code/modules/spells/roguetown/acolyte/eora.dm
> +	return FALSE
```suggestion
	to_chat(user, span_warning("The targeted location is blocked. The flowers of Eora refuse to grow."))
	return FALSE
```

2024-11-30 17:16 UTC, Gyrandola commented on code/modules/spells/roguetown/acolyte/eora.dm
> +//Eora content from Stonekeep
```suggestion
```

2024-11-30 17:16 UTC, Gyrandola commented on code/modules/clothing/rogueclothes/hats/hats.dm
> +			to_chat(user, span_warning("<span class='warning'>I feel at peace. <b style='color:pink'>Why would I want anything else?</b></span>"))
```suggestion
			to_chat(user, span_warning("I feel at peace. <b style='color:pink'>Why would I want anything else?</b>"))
```

2024-11-30 18:22 UTC, Gyrandola approved these changes

2024-11-30 18:23 UTC, merged

2024-12-01 01:31 UTC, Frienderanian commented
Can Eora still be the Goddess of Lust? I kind of like that. I feel like it can be spun in a positive direction. Lust has driven men to do great things throughout all of history and I kind of like Eora as a god bringing validation to the real feelings of Lust that Men typically have and shouldn't be ashamed of. :)